### ISSUE TITLE
RuntimeError: arguments are located on different GPUs

### ISSUE THREAD

**Issue by chihyaoma** [jihunchoi/recurrent-batch-normalization-pytorch#2]
Hi, thank you for sharing with us the implemented BN-LSTM. I have successfully used it when this is only one GPU on my machine. 

However, if I use the data parallel layer for multiple GPUs (4 in my machine),
```
model = torch.nn.DataParallel(model).cuda()
```
There is an error:
`
RuntimeError: arguments are located on different GPUs at /py/conda-bld/pytorch_1493677666423/work/torch/lib/THC/generic/THCTensorMathBlas.cu:232`

The error occurs at [wh = torch.mm(h_0, self.weight_hh)](https://github.com/jihunchoi/recurrent-batch-normalization-pytorch/blob/master/bnlstm.py#L143)

Has anybody faced the same issue?

**Comment by jihunchoi** [comment]
Hello, thank you for your interest on this stale repo!
As you know, the implementation is not complete, including yours and other issues.
I'll fix the problems including this one once I have some spare time, but these days I've got too busy and I think I would be not able to modify the bugs for a few weeks...
It'll be great if you give the repo a PR resolving the issue!

**Comment by furlat** [comment]
Any update?

best

**Comment by jihunchoi** [comment]
Fixed.
The problem occurred due to non-standard module registration lines. Now it is fixed to use the standard guideline.

**Comment by Tord-Zhang** [comment]
@jihunchoi I meet the same problem when I am trying to implement my custom LSTM. What causes this problem? and how did you fix it?  Thanks.

**Comment by jihunchoi** [comment]
@mangdian I’m not aware much of the exact implementation, but my practice is to register all parameters, buffers, and (sub)modules to a custom module.
This is automatically done for standard pytorch components (e.g. nn.Module, nn.Parameter, nn.ModuleList, etc.), however if non-standard components e.g. list, dictionary are used, they are not registered to the module and not copied to other GPUs.
In my case, it was a list that causes the problem, and it could be fixed by replacing lists with nn.ModuleList. I recommend reading documentation about nn.ModuleDict, nn.ParameterList, etc.
